### ISSUE TITLE
Priority Condition

### ISSUE THREAD

**Issue by clearloop** [lark-in-today/web#1]
The Priority condition of the development.

# Features
+ Free User Interface
+ Mini Programs (iframe stack)

## Instant Messaging (IRC)

Mock the UI of wechat.

## News / Articles (RSS) 

__API__:  `:id/:channel`

# Todo
## Primary
+ [ ] login page - auth - tweetnacl
+ [ ] chats page - ws
+ [ ] contacts page - update and pull animation
+ [ ] config page - auto-config
+ [ ] article page - webview

## Vendors
+ [ ] keyboard - richtext
+ [ ] typography - markdown render
+ [ ] animation 
  + [ ] navigation - second floor
  + [ ] update and loading
+ [ ] routes - route system
